### ISSUE TITLE
chore: FlutterFloaty height and width are not dynamic 

### ISSUE THREAD

**Issue by imrikim** [JordyHers/flutter_floaty#29]
**FlutterFloaty height and width are not dynamic **

on builder I pass Expandable item, once it is clicked it shows longer and wider layout, and that cause FlutterFloaty to be overflowed 

**Requirements**

- Need to handle the edge case where the builder's content changes its width and/or height dynamically after the initial build.

**Comment by JordyHers** [comment]
@imrikim issue resolved in release `0.2.0`

**Comment by imrikim** [comment]
Amazing !
thank you @JordyHers 👍

**Comment by imrikim** [comment]
closing the issue
